### PR TITLE
Users can now delete their profile image.

### PR DESCRIPTION
**Pull request by rasmusebbesen**
- Added a check for empty profile image, enabling a user to delete it.

### CODE REVIEW

**Comment by Casperhr** [comment]
Please test

This looks like updating a user, but without picking a new image will remove the image on the user

**Comment by rasmusebbesen** [comment]
That is absolutely correct. We have no way of verifying if the user chooses to remove his image or simply didn't provide one.

**Comment by Casperhr** [comment]
you can add like "remove" on the image key

and then string check on that

**Comment by Casperhr** [comment]
Else you have to make a separate action for removing the image

**Comment by rasmusebbesen** [comment]
Think the file picker mechanism provided by nodes-ui needs to reflect if the image should be deleted. A hidden field called "delete-image" that react to user interaction on the "x"

**Comment by rasmusebbesen** [comment]
Updated the PR @Casperhr

**Pull request merged**
